### ISSUE TITLE
Endpoints: Get overall and coin statistics

### ISSUE THREAD

**Issue by marcogerstmann** [marcogerstmann/cryptoportfolio-service#16]
# Task Dependencies
Depends on: https://github.com/marcogerstmann/cryptoportfolio-service/issues/6

# Description
Similar to the Java version of cryptoportfolio-service.

The two endpoints `GET /api/v1/portfolio/statistics` (overall statistics) and `GET /api/v1/portfolio/statistics/coin` (coin statistics) need to be implemented.

They can be done in the same task, because the overall statistics will reuse most of the logics of the coin statistics, just accumulating the values.

# To Do
- [x] Add unit test support with Jest
- [x] Add a `MonetaryAmount` interface instead of just using numbers
- [x] Finish `TransactionStatisticsService`
- [x] Implement coin statistics calculation
- [x] Implement overall statistics calculation
- [x] Compare results from CoinMarketCap with my Portfolio on Koinly
- [ ] Add unit tests for coin statistics calculation
- [ ] Add unit tests for overall statistics calculation
- [ ] Review leftover `// TODO 16` comments

**Comment by marcogerstmann** [comment]
# To Do
- [ ] Add a `MonetaryAmount` interface instead of just using numbers
- [ ] Finish `TransactionStatisticsService`
- [ ] Implement coin statistics calculation
- [ ] Implement overall statistics calculation
